version: "3"
services:
  app:
    build:
      context: .
      network: "host"
    restart: on-failure
    command: >
      bash -c "python start.py"
    env_file:
      - .env.config
    network_mode: "host"
