version: "3"
services:
  api_app:
    build:
      context: .
      network: "host"
    restart: on-failure
    command: >
      bash -c "python3.10 start.py"
    volumes:
      - ./logs:/opt/app/logs
    env_file:
      - .env.config
    network_mode: "host"
