version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8087:8087"
    restart: on-failure
    command: >
      bash -c "python start.py"
    env_file:
      - .env.config

  redis:
    image: redis
